[tool.poetry]
name = "aoc2022"
version = "0.1.0"
description = ""
authors = ["Hector Brown <hectorjbrown@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"
tqdm = "^4.64.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
